// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvqGCGKCvTiVgXlBpkO_IgMgbp4Pd-Qr4',
    appId: '1:896241300467:web:d7ee69e7e610b955009886',
    messagingSenderId: '896241300467',
    projectId: 'riyads-first-note-app',
    authDomain: 'riyads-first-note-app.firebaseapp.com',
    storageBucket: 'riyads-first-note-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wdvOXTC5OGpptpSSr0KzT__zJq35UvI',
    appId: '1:896241300467:android:a2a94698dbb75384009886',
    messagingSenderId: '896241300467',
    projectId: 'riyads-first-note-app',
    storageBucket: 'riyads-first-note-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUhRFFFo_R5d3ShT_obNxDh-8SxNYJVgk',
    appId: '1:896241300467:ios:44af79430924e341009886',
    messagingSenderId: '896241300467',
    projectId: 'riyads-first-note-app',
    storageBucket: 'riyads-first-note-app.appspot.com',
    iosClientId: '896241300467-dpm96oks99sf0oh3ljr8vam3ffb0nteq.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUhRFFFo_R5d3ShT_obNxDh-8SxNYJVgk',
    appId: '1:896241300467:ios:44af79430924e341009886',
    messagingSenderId: '896241300467',
    projectId: 'riyads-first-note-app',
    storageBucket: 'riyads-first-note-app.appspot.com',
    iosClientId: '896241300467-dpm96oks99sf0oh3ljr8vam3ffb0nteq.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
